/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b12683668b16073a39d09f96913fc9bd)
declare namespace Cloudflare {
  interface Env {
    EXTERNAL_API_CACHE: KVNamespace;
    OPENAI_API_KEY: string;
    ANTHROPIC_API_KEY: string;
    RESEND_API_KEY: string;
    OPENROUTER_API_KEY: string;
    AUTH_SECRET: string;
    POSTGRES_URL: string;
    GITHUB_CLIENT_ID: string;
    GITHUB_CLIENT_SECRET: string;
    GITHUB_APP_ID: string;
    GITHUB_APP_PRIVATE_KEY: string;
    GITHUB_APP_BASE_URL: string;
    GITHUB_WEBHOOK_SECRET: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    SLACK_SIGNING_SECRET: string;
    SLACK_CLIENT_ID: string;
    SLACK_CLIENT_SECRET: string;
    NODE_ENV: string;
    FLY_API_KEY: string;
    KOYEB_API_KEY: string;
    EXA_API_KEY: string;
    STRIPE_API_KEY: string;
    AXIOM_API_KEY: string;
    AXIOM_DATASET: string;
    NEXT_PUBLIC_POSTHOG_KEY: string;
    NEXT_PUBLIC_POSTHOG_HOST: string;
    STRIPE_BLINK_USAGE_PRICE_ID: string;
    STRIPE_WEBHOOK_SECRET: string;
    METRONOME_BEARER_TOKEN: string;
    METRONOME_WEBHOOK_SECRET: string;
    METRONOME_RATE_CARD_ID: string;
    BLINK_API_URL: string;
    GRAFANA_OTEL_API_KEY: string;
    GRAFANA_OTEL_HTTP_ENDPOINT: string;
    OTLP_HTTP_TRACES_ENDPOINT: string;
    OTLP_HTTP_HEADER_AUTHORIZATION: string;
    XAI_API_KEY: string;
    DEBUG: string;
    LOG_LEVEL: string;
    GOOGLE_API_KEY: string;
    WORKSPACE: DurableObjectNamespace<import("./src/index").Workspace>;
    CHAT: DurableObjectNamespace<import("./src/index").Chat>;
    COMMAND_LINE_AUTH: DurableObjectNamespace<
      import("./src/index").CommandLineAuth
    >;
    AGENT_DEPLOYMENT: DurableObjectNamespace<
      import("./src/index").AgentDeployment
    >;
    REPO_STORAGE: R2Bucket;
    USER_FILES: R2Bucket;
    STATIC_DEPLOYMENTS: R2Bucket;
    HYPERDRIVE: Hyperdrive;
    BROWSER: Fetcher;
    AGENT_STORE: KVNamespace;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "OPENAI_API_KEY"
        | "ANTHROPIC_API_KEY"
        | "RESEND_API_KEY"
        | "OPENROUTER_API_KEY"
        | "AUTH_SECRET"
        | "POSTGRES_URL"
        | "GITHUB_CLIENT_ID"
        | "GITHUB_CLIENT_SECRET"
        | "GITHUB_APP_ID"
        | "GITHUB_APP_PRIVATE_KEY"
        | "GITHUB_APP_BASE_URL"
        | "GITHUB_WEBHOOK_SECRET"
        | "GOOGLE_CLIENT_ID"
        | "GOOGLE_CLIENT_SECRET"
        | "SLACK_SIGNING_SECRET"
        | "SLACK_CLIENT_ID"
        | "SLACK_CLIENT_SECRET"
        | "NODE_ENV"
        | "FLY_API_KEY"
        | "KOYEB_API_KEY"
        | "EXA_API_KEY"
        | "STRIPE_API_KEY"
        | "AXIOM_API_KEY"
        | "AXIOM_DATASET"
        | "NEXT_PUBLIC_POSTHOG_KEY"
        | "NEXT_PUBLIC_POSTHOG_HOST"
        | "STRIPE_BLINK_USAGE_PRICE_ID"
        | "STRIPE_WEBHOOK_SECRET"
        | "METRONOME_BEARER_TOKEN"
        | "METRONOME_WEBHOOK_SECRET"
        | "METRONOME_RATE_CARD_ID"
        | "BLINK_API_URL"
        | "GRAFANA_OTEL_API_KEY"
        | "GRAFANA_OTEL_HTTP_ENDPOINT"
        | "OTLP_HTTP_TRACES_ENDPOINT"
        | "OTLP_HTTP_HEADER_AUTHORIZATION"
        | "XAI_API_KEY"
        | "DEBUG"
        | "LOG_LEVEL"
        | "GOOGLE_API_KEY"
      >
    > {}
}
