import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import stringify from "json-stable-stringify";
import { generateTemplates } from "../lib/templates";

const main = async () => {
  const templates = await generateTemplates();
  const templatesDir = join(import.meta.dirname, "..", "init-templates");

  // Generate the index.ts file
  const outputPath = join(templatesDir, "index.ts");
  const output = `// This file is auto-generated by \`bun run gen-templates\`
// Do not edit this file directly. Instead, edit the template files in src/cli/init-templates/*/ and run the generation script.

export const templates = ${stringify(templates, { space: 2 })} as const;

export type TemplateId = keyof typeof templates;
`;

  await writeFile(outputPath, output);
  console.log(`Generated ${outputPath}`);
};

main().catch((error) => {
  console.error("Error generating templates:", error);
  process.exit(1);
});
