#!/usr/bin/env bun
import { join } from "node:path";

const wrapperNode = join(__dirname, "../src/node/wrapper-node.ts");

let result = await Bun.build({
  entrypoints: [wrapperNode],
  target: "node",
  format: "esm",
  minify: true,
  packages: "bundle",
});

let output = result.outputs[0];
if (!output) {
  throw new Error("No output generated");
}

await Bun.write(
  join(__dirname, "../src/node/wrapper-node.generated.ts"),
  `
// This file has been generated by the ${import.meta.filename} script.
// Do not edit this file manually.

export default ${JSON.stringify(await output.text())}
`.trim()
);

const wrapperLambda = join(__dirname, "../src/lambda/wrapper-lambda.ts");

result = await Bun.build({
  entrypoints: [wrapperLambda],
  target: "node",
  format: "esm",
  packages: "bundle",
});

output = result.outputs[0];
if (!output) {
  throw new Error("No output generated");
}

await Bun.write(
  join(__dirname, "../src/lambda/wrapper-lambda.generated.ts"),
  `
// This file has been generated by the ${import.meta.filename} script.
// Do not edit this file manually.

export default ${JSON.stringify(await output.text())}
`.trim()
);
